### ISSUE TITLE
No module named 'DNS'

### ISSUE THREAD

**Issue by gugelhupf50** [dhs-ncats/trustymail#144] opened 2023-11-09 20:18 UTC
# 🐛 Summary #

What's wrong? Please be specific.
Traceback (most recent call last):
  File "/Users/fgs/Library/Python/3.9/bin/trustymail", line 5, in <module>
    from trustymail.cli import main
  File "/Users/fgs/Library/Python/3.9/lib/python/site-packages/trustymail/cli.py", line 61, in <module>
    from . import trustymail
  File "/Users/fgs/Library/Python/3.9/lib/python/site-packages/trustymail/trustymail.py", line 15, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'

## To reproduce ##

1. run trustymail

## Expected behavior ##
evaluate domain and output csv file with results

## Any helpful log output or screenshots ##
Traceback (most recent call last):
  File "/Users/fgs/Library/Python/3.9/bin/trustymail", line 5, in <module>
    from trustymail.cli import main
  File "/Users/fgs/Library/Python/3.9/lib/python/site-packages/trustymail/cli.py", line 61, in <module>
    from . import trustymail
  File "/Users/fgs/Library/Python/3.9/lib/python/site-packages/trustymail/trustymail.py", line 15, in <module>
    import DNS
ModuleNotFoundError: No module named 'DNS'

**Comment by jsf9k** [comment] 2023-11-09 20:20
This is a duplicate of #41, a known issue with case-insensitive filesystems under OSX.

**Closed as not planned by jsf9k** 2023-11-09 20:20 UTC
Labels: wontfix
